# Álgebra Linear para Ciência de Dados

## Conceitos Básicos

Escrevemos $\vec{V} = \vec{V}_{s \times 1}$ para denotar um vetor de dimensão $s$, ou seja, um vetor com $S$ linha(s) e $1$ coluna:

$$
\vec{V} = \begin{bmatrix}
S_{1} \\
S_{1} \\
... \\
S_{s}
\end{bmatrix}
$$

In [38]:
# Utilizando a biblioteca NumPy:
import numpy as np


# Declarando S = 5:
s = 5


# Criando o vetor "v" com 5 colunas e 1 linha, com elementos variando entre 1 e 100:
v = np.random.randint(low=1, high=100, size=(s, 1))
print(v)

[[44]
 [39]
 [65]
 [28]
 [74]]


Seja $\vec{V} = \vec{V}_{s \times 1}$ e $c \in \mathbb{R}$ um escalar. Define-se produto $c \times \vec{V} = c\vec{V}$ como:

$$
c\vec{V} = \begin{bmatrix}
c \times v_{1} \\
c \times v_{1} \\
... \\
c \times v_{s}
\end{bmatrix}
$$

In [ ]:
# Utilizando a biblioteca NumPy:
import numpy as np


# Criando o vetor "v" com 5 linhas e 1 coluna, com elementos de 1 a 5:
v = np.array([[1], [2], [3], [4], [5]])


# Declarando o escalar "c" com valor 10:
c = 10


# Realizando o produto:
result = c * v
print(result)

[[10]
 [20]
 [30]
 [40]
 [50]]


Sejam $\vec{V} = V_{s \times 1}$ e $\vec{W} = W_{s \times 1}$. Define-se a soma de dois vetores com:

$$
\vec{V} + \vec{W} = \begin{bmatrix}
v_{1} + w_{1} \\
v_{1} + w_{1} \\
... \\
v_{s} + w_{s}
\end{bmatrix}
$$

In [ ]:
# Utilizando a biblioteca NumPy:
import numpy as np


# Declarando os vetores "v" e "w" de mesma dimensão (3 linhas, 1 coluna):
v = np.array([[1], [2], [3]])
w = np.array([[10], [20], [30]])


# Realizando a soma:
sum = v + w
print(sum)

[[11]
 [22]
 [33]]


Escrevemos $A = A_{n \times m}$ para matriz de dimensão $n \times m$. Ou seja, $n$ linhas e $m$ colunas.

$$
A = \begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} & a_{1,m} \\
a_{2,1} & a_{2,2} & a_{2,3} & a_{2,m} \\
... & ... & ... & ... \\
a_{n,1} & a_{n,2} & a_{n,3} & a_{n,m}
\end{bmatrix}
$$

> Quando $A = A_{n \times m}$, dizemos que $A$ é uma matriz *quadrada* de fator $n$.

## Multiplicação por Escalar

Seja $A = A_{n \times m}$ e $C \in \mathbb{R}$. Define-se a multiplicação de $A_{n \times m}$ por $C$:

$$
C \times A = \begin{bmatrix}
ca_{1,1} & ca_{1,2} & ca_{1,m} \\
ca_{2,1} & ca_{2,2} & ca_{2,m} \\
... & ... & ... \\
ca_{n,1} & ca_{n,2} & ca_{n,m}
\end{bmatrix}
$$

Seja $A = A_{n \times m}$ e $B = B_{n \times m}$ duas matrizes de mesma dimensão. A soma $A + B$ é uma matriz $n \times m$ em que:

$$
A + B = \begin{bmatrix}
a_{1,1} + b_{1,1} & a_{1,2} + b_{1,2} & a_{1,m} + b_{1,m} \\
a_{2,1} + b_{2,1} & a_{2,2} + b_{2,2} & a_{2,m} + b_{2,m} \\
... & ... & ... \\
a_{n,1} + b_{n,1} & a_{n,2} + b_{n,2} & a_{n,m} + b_{n,m} \\
\end{bmatrix}
$$

## Produto de Duas Matrizes

Sejam $A = A_{n \times m}$ e $B = B_{n \times p}$ duas matrizes. O produto $A \times B$ é uma matriz $n \times p$ em que:

$$
A \times B = \begin{bmatrix}
\sum_{i=1}^{m} a_{1,i} \times b_{i,j} & \sum_{i=1}^{m} a_{1,i} \times b_{i,p} \\
... & ... \\
\sum_{i=1}^{m} a_{n,i} \times b_{i,j} & \sum_{i=1}^{m} a_{n,i} \times b_{i,p}
\end{bmatrix}
$$

### Exemplo

Para $A_{2 \times 3}$ e $B_{3 \times 1}$, temos:

$$
A = \begin{bmatrix}
1 & 0 & 1 \\
2 & 2 & 0
\end{bmatrix}
\times
B = \begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}
$$

gerando:

$$
A \times B = \begin{bmatrix}
(1 \times 1) + (0 \times 0) + (1 \times 0) \\
(2 \times 1) + (2 \times 0) + (0 \times 0)
\end{bmatrix}
$$

resultando em:

$$
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$

## Matriz Transposta / Vetor Transposto

A matriz transposta de $A$ é denotado por $A^t$ e é definida por:

$$
A^t = \begin{bmatrix}
a_{1,1} & a_{2,1} & a_{n,1} \\
a_{2,1} & a_{2,2} & a_{n,2} \\
... & ... & ... \\
a_{1,m} & a_{2,m} & a_{n,m}
\end{bmatrix}
$$

O vetor transposto de $V$ é denotado por $V^t$ e é definido por:

$V^t = \begin{bmatrix}N_{1} & N_{2} & ... & N_{s}\end{bmatrix}$

## Produto Interno

Sejam $V = V_{s,1}$ e $W_{s,1}$. Define-se o produto interno de dois vetores com:

$V^t \times W = N_{1} \times W_{1} + N_{2} \times W_{2} + ... + N_{s} \times W_{s} \in \mathbb{R}$

## Notações e Definição

Sejam $A = A_{n,m}$ uma matriz Real com $n$ linhas e $m$ colunas e $V = V_{s,1}$ um vetor com $s$ linhas:

1. $A^t$ é a matriz transposta de $A$, $V^t$ é o vetor transposto de $V$
2. $det(A_{n,m}) = det(A) = |A|$ é a determinante de $A$
3. $T_{n}(A) = T_{n}A$ é o traço de $A$ (soma dos elementos da Diagonal Principal de $A$)
4. $A^{-1}$ é a inversa de $A$, se $A$ admitir inversa
5. $dim(A)$ é a dimensão de $A$, em geral, no formato $n$ linhas e $m$ colunas
6. $P(A)$ é o Posto de $A$. Ou seja, é a ordem da maior submatriz de determinante não nulo de $A$
7. $I_{n} = I$ é a Matriz Identidade de ordem $n$

## Definições e Resultados Matriciais

### Dependência Linear de Vetor

Sejam $V_{1}, V_{2}, ..., V_{n}$ vetores, cada um com $n$ linhas, $V_{i} \in \mathbb{R}^n$, $i = 1, ..., m$.

O conjunto $\{V_{1}, ..., V_{m}\}$ é um conjunto de vetores Linearmente Independentes (LI) se $C_{1} \times V_{1} + ... + C_{m} \times V_{m} = 0 \Rightarrow \vec{0}$

Caso contrário, dizemos que $\{V_{1}, ..., V_{m}\}$ é um conjunto  Linearmente Dependente (LD).

1. Se $A$ admite inversa, então $A$ é dita não singular. Caso contrário, $A$ é singular
2. Se $A_{n,m}$ adminte inversa, $A^{-1}$, então é única
3. $A = A^{-1} = I_{m} = A^{-1} \times A$
4. $(A^{-1}) = A$
5. $A_{n,m}$ e $B_{n,m}$ $\tilde{n}$ singular $\Rightarrow (AB)^{-1} = B^{-1} \times A^{-1}$
6. $A_{n,m}$ $\tilde{n}$ singular e $K \neq 0$ um escalar $\Rightarrow (KA)^{-1} = (\frac{1}{K} \times (A)^{-1})$

> Uma matriz $A_{n,m}$ é dita singular então $det(A_{n,m}) = 0$. Ou seja, $\tilde{n}$ admite inversa.

## Propriedades

### Matriz Transposta

1. $A \times A^t \Rightarrow A$ é simétrica
2. $A \times A^t$ e $A^t \times A$ é simétrica
3. $A$ e $B$ são matrizes, $\exists AB \Rightarrow (A \times B)^t = B^tA^t$

### Determinantes

1. $A_{n,m}$ , $B_{n,m} \Rightarrow det(AB) = det(A) \times det(B)$
2. $det(A_{n,m}) = 0 \Rightarrow A$ é singular

## Traço de uma Matriz

É possível denotar o *traço* de uma matriz $T_{n} = T_{n}(B \times A)$ se $AB$ e $BA$ estiverem definidos.